# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: source_location
    values: 
      - '/src/terraform'
  #- name: variables_file_path
   # values:
    #  - './Vars/dev.tfvars'
  - name: environment_name
    values:
      - 'dev'
  - name: service_principle_name
    values:
      - 'devopstoazure'
  - name: backend_storage_resourceGroupName
    values:
      - 'rg-tf'
  - name: backend_storage_account_name
    values:
      - 'tfstfjan2023acc'
  - name: backend_storage_container_name
    values:
      - 'tfstatefile'
  - name: backend_storage_state_file_name
    values:
      - 'devops.prd.tfstate'

pool:
  name: nareshpcagent
  #vmImage: ubuntu-latest

stages:
  - stage: validate
    jobs:
      - template: validate.yml
        parameters:
          source_location :  ${{ parameters.source_location }}
          #variables_file_path :  ${{ parameters.variables_file_path }}
          environment_name :  ${{ parameters.environment_name }}
          service_principle_name :  ${{ parameters.service_principle_name }}
          backend_storage_resourceGroupName :  ${{ parameters.backend_storage_resourceGroupName }}
          backend_storage_account_name :  ${{ parameters.backend_storage_account_name }}
          backend_storage_container_name :  ${{ parameters.backend_storage_container_name }}
          backend_storage_state_file_name :  ${{ parameters.backend_storage_state_file_name }}
          

  - stage: deploy_${{ parameters.environment_name }}
    jobs:
      - deployment: dev
        timeoutInMinutes: 0
        displayName: deploy_${{ parameters.environment_name }}
        environment: ${{ parameters.environment_name }} 
        strategy:
         runOnce:
           deploy:
             steps:
              - template: deploy.yml
                parameters:
                  source_location :  ${{ parameters.source_location }}
                  #variables_file_path :  ${{ parameters.variables_file_path }}
                  environment_name :  ${{ parameters.environment_name }}
                  service_principle_name :  ${{ parameters.service_principle_name }}
                  backend_storage_resourceGroupName :  ${{ parameters.backend_storage_resourceGroupName }}
                  backend_storage_account_name :  ${{ parameters.backend_storage_account_name }}
                  backend_storage_container_name :  ${{ parameters.backend_storage_container_name }}
                  backend_storage_state_file_name :  ${{ parameters.backend_storage_state_file_name }}
